version: '3'
services:
    gohelloworld:
        build: .
        image: gohelloworld:latest
        ports: 
            - "8080:8080"
    gobase:
        image: golang:latest
        working_dir: "/app/src"
        volumes: 
            - "./:/app"
    awscli:
        image: amazon/aws-cli
        working_dir: "/app"
        env_file: 
            - ./aws.env
    security:
        image: owasp/zap2docker-weekly
        volumes: 
            - "./output:/output"
        links: 
            - "gohelloworld"
