FROM node:14-alpine

SHELL ["/bin/bash", "-c"]

ENV NEXT_TELEMETRY_DISABLED 1

USER root:root
ENV HOME /root

RUN apt-get update

# INSTALL make
RUN apt-get install -y make 

# SETUP APP
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
RUN npm install

CMD npx wdio run wdio.conf.browserstack.js
