version: '3'
services:
    gohelloworld:
        build: .
        image: gohelloworld:latest
        ports: 
            - "8080:8080"
        healthcheck:
            test: curl --fail http://localhost:8080 || exit 1
            interval: 10s
            retries: 50
            start_period: 20s
            timeout: 2s
    gobase:
        image: golang:latest
        working_dir: "/app/src"
        volumes: 
            - "./:/app"
    awscli:
        image: amazon/aws-cli
        working_dir: "/app"
        env_file: 
            - ./aws.env
    security:
        image: owasp/zap2docker-weekly
        volumes: 
            - "./output:/output"
        depends_on:
            gohelloworld:
                condition: service_healthy
