FROM registry.gitlab.int.bell.ca/entpay/ace/images/react-cicd:1

SHELL ["/bin/bash", "-c"]

ENV NEXT_TELEMETRY_DISABLED 1

# INSTALL JAVA
# RUN apk update
RUN apk add --update --no-cache openjdk8

# SETUP APP
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./browser-logs.js ./tools/testing/browser-logs.js
COPY package.json .
RUN npm install

CMD npx wdio run wdio.conf.browserstack.js
