name: Main CI (TEST)

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:
      types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: go-hello-world
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:

  buildtest:
    runs-on: ubuntu-latest
        
    steps:

    - name: checkout repo
      uses: actions/checkout@v2

    # - name: Create DynamboDB Table in AWS - To store metadata (one-time)
    #   run: make create_table
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: us-east-2

    - name: Create tags in DynamboDB Table in AWS - Metadata for this commit
      run: make create_tags
      env:
        PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
