# These are pipeline steps we're testing that aren't GSD-like yet
name: Playground

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:

  golang-security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ynniss/golang-security-action@master
      with:
        CODE_PATH: "./src/" 

  gosec-scanner:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
