on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #     types: [opened, synchronize, reopened]
  workflow_dispatch:

name: Security Scans

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: security
             # make security should run all scans in parallel using a docker-compose file with 1 service per scan
        run: make security

        # This would be most flexible if done at the end of each security scan above as part of it's run (might be tricky to get github context)
        # Alternatively, archive a path that they ALL write to....
      - name: Archive security results
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: output/security-report.txt

  call-verify:
    uses: ./.github/workflows/verify.yml
    needs: security-scan
    secrets: inherit
