on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: security

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Archive security results
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: output/security-report.txt