on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Verify

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: contino/gsd-verification-rules    
    
    - name: Run all verification rules from gsd-verification-rules
      run: make verify
