on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Verify

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Run all verification rules from gsd-verification-rules
      run: make verify
