on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Verify
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TOKEN: ${{ secrets.TOKEN }}
  AWS_DEFAULT_REGION: us-east-2

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "🎉 The commit ID of the artifact is: $GITCOMMIT"
        echo "GITCOMMIT=$GITCOMMIT" >> $GITHUB_ENV
        echo "🎉 The dynamodb table is: $DYNAMODB_TABLE"
        echo "DYNAMODB_TABLE=$DYNAMODB_TABLE" >> $GITHUB_ENV
      env:
        GITCOMMIT: ${{ github.sha }}
        DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}

    - name: Check out gsd-verification-rules repo
      uses: actions/checkout@v2
      with:
        repository: contino/gsd-verification-rules
        ref: main
        path: gsd-verification-rules
        ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
    
    - name: Run all verification rules
      run: cd gsd-verification-rules && make verify

