on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Verify

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

    - name: Check public
      uses: actions/checkout@v2  
      with:
        repository: contino/docker-aws-cli
        ref: master        path: drewtestpublic
      
-   name: Setup SSH Keys and known_hosts (for RO permission to gsd-verification-rules repo)
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Check out gsd-verification-rules (private repo)
      uses: actions/checkout@v2
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock      
      with:
        repository: contino/gsd-verification-rules
        ref: main
        path: drewtest
    
    - name: Run all verification rules from gsd-verification-rules
      run: make verify
