on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Zap Security Scan

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: security
        run: make security
      - name: Archive security results
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: output/security-report.txt
